#!/bin/bash
# 운영서버 cron 설정 스크립트

echo "🔧 운영서버 자동 배포 설정"
echo ""
echo "운영서버에서 다음 명령어를 실행하세요:"
echo ""
echo "1. 스크립트 복사:"
echo "   mkdir -p /home/server/SERVER/scripts"
echo "   # prod-auto-deploy.sh 파일을 복사"
echo "   chmod +x /home/server/SERVER/scripts/prod-auto-deploy.sh"
echo ""
echo "2. 첫 실행 테스트:"
echo "   /home/server/SERVER/scripts/prod-auto-deploy.sh"
echo ""
echo "3. Crontab 설정 (5분마다 실행):"
echo "   crontab -e"
echo "   # 다음 줄 추가:"
echo "   */5 * * * * /home/server/SERVER/scripts/prod-auto-deploy.sh > /dev/null 2>&1"
echo ""
echo "4. 로그 확인:"
echo "   tail -f /home/server/deploy.log"
echo ""
echo "✨ 설정 완료 후 개발서버에서 배포하면 5분 이내에 자동 배포됩니다!"